export const ACTIONS = {
  /**** NEW ACTIONS START ****/
  NEWS_FETCH_START: "NEWS_FETCH_START",
  NEWS_FETCH_SUCESS: "NEWS_FETCH_SUCCESS",
  NEWS_FETCH_ERROR: "NEWS_FETCH_ERROR",
  /**** NEW ACTIONS END ****/
};
